# The block to convert to
block: GOLDEN_BLOCK

# Blocks to NOT convert
blacklist:
  - AIR
  - CAVE_AIR
  - VOID_AIR
  - WATER
  - LAVA
  - BARRIER
  - BEDROCK
  - END_PORTAL
  - END_PORTAL_FRAME
  - END_GATEWAY
  - STRUCTURE_BLOCK
  - COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - SPAWNER

# Whether to convert blocks when left/right-clicking blocks
click: true
