name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.13

commands:
  midas:
    description: Main command for Midas Touch
    aliases:
      - mt
      - midastouch
    permission: midas.command

permissions:
  midas.command:
    description: Allows the player to use /midas
