name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: XyFf5IBt
      curseforge: 897236
    secrets: inherit
    permissions:
      contents: write
